steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'artifacts-claas-com-containertechnology-jfrog-platform'
    command: |
      jf helm pull oci://manuaccess.jfrog.io/manu-helmoci/bitnamicharts/nginx --version 19.0.0